-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK AS B
JOIN BOOK_SALES AS S
 ON S.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE >= "2022-01-01" AND SALES_DATE < "2022-02-01"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;